services:
  pms:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - default
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=pms'
      - 'POSTGRES_PASSWORD=1234'
    ports:
      - '5432'
    networks:
      - default

networks:
  default:
    driver: bridge