CREATE TYPE "role" AS ENUM ('GUEST', 'PATIENT', 'DOCTOR', 'ADMIN')


CREATE TABLE "user_account" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "role" role NOT NULL DEFAULT 'GUEST',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "patient" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_account_id" int,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "date_of_birth" date NOT NULL,
  "gender" varchar,
  "contact_number" varchar,
  "email" varchar,
  "address" text,
  "emergency_contact" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "doctor" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_account_id" int,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "specialty" varchar,
  "contact_number" varchar,
  "email" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "appointment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" int,
  "doctor_id" int,
  "appointment_date" timestamp NOT NULL,
  "reason" text,
  "status" varchar DEFAULT ('SCHEDULED'),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "medical_record" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" int,
  "record_date" timestamp NOT NULL,
  "description" text,
  "file_path" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "prescription" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "appointment_id" int,
  "medication" varchar NOT NULL,
  "dosage" varchar,
  "instructions" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "billing" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" int,
  "appointment_id" int,
  "amount" decimal NOT NULL,
  "status" varchar DEFAULT ('PENDING'),
  "billing_date" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

ALTER TABLE "patient" ADD FOREIGN KEY ("user_account_id") REFERENCES "user_account" ("id");

ALTER TABLE "doctor" ADD FOREIGN KEY ("user_account_id") REFERENCES "user_account" ("id");

ALTER TABLE "appointment" ADD FOREIGN KEY ("patient_id") REFERENCES "patient" ("id");

ALTER TABLE "appointment" ADD FOREIGN KEY ("doctor_id") REFERENCES "doctor" ("id");

ALTER TABLE "medical_record" ADD FOREIGN KEY ("patient_id") REFERENCES "patient" ("id");

ALTER TABLE "prescription" ADD FOREIGN KEY ("appointment_id") REFERENCES "appointment" ("id");

ALTER TABLE "billing" ADD FOREIGN KEY ("patient_id") REFERENCES "patient" ("id");

ALTER TABLE "billing" ADD FOREIGN KEY ("appointment_id") REFERENCES "appointment" ("id");
